#!/bin/sh

#    Home Net Control - Monitorizes devices connected to net and notify
#    according with its type. Also monitorizes the bandwidth.
#    Copyright (C) 2016  bercianor  (https://github.com/bercianor)
#    
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

### BEGIN INIT INFO
# Provides:          homenetcontrol
# Required-Start:    $local_fs $network $name $time $syslog
# Required-Stop:     $local_fs $network $name $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       HomeNetControl daemon
### END INIT INFO

. /lib/lsb/init-functions

NAME="HomeNetControl"
PACKAGE="homenetcontrol"
DAEMON="/usr/local/bin/$PACKAGE"
ARGS="-l"
PIDFILE="/var/run/$PACKAGE.pid"
LOGFILE="/var/log/$PACKAGE.run.log"

# Check for missing binaries
test -x $DAEMON || {
    log_failure_msg "$DAEMON not installed";
    exit 5;
}

case "$1" in
    start)
        # Checked the PID file exists and check the actual status of process
        if [ -e $PIDFILE ]; then
            status_of_proc --pidfile $PIDFILE $DAEMON $NAME >/dev/null && status="0" || status="$?"
            # If the status is SUCCESS then don't need to start again.
            if [ $status = "0" ]; then
                log_warning_msg "Service already running\n"
                exit 0
            else
                # Start the daemon.
                log_daemon_msg "Starting the process1" "$NAME\n"
                start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --startas /bin/bash -- -c "exec $DAEMON $ARGS > $LOGFILE 2>&1"
                log_end_msg $?
                exit $?
            fi
        else
            # Start the daemon.
            log_daemon_msg "Starting the process2" "$NAME\n"
            start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --startas /bin/bash -- -c "exec $DAEMON $ARGS > $LOGFILE 2>&1"
            log_end_msg $?
            exit $?
        fi
        ;;
    stop)
        # Stop the daemon.
        if [ -e $PIDFILE ]; then
            status_of_proc --pidfile $PIDFILE $DAEMON $NAME >/dev/null && status="0" || status="$?"
            if [ "$status" = "0" ]; then
                log_daemon_msg "Shutting down the process" "$NAME\n"
                start-stop-daemon --stop --quiet --oknodo --retry TERM/30/KILL/5 --pidfile $PIDFILE && {
                    /bin/rm -rf $PIDFILE;
                    log_end_msg 0;
                    exit 0;
                } || {
                    log_end_msg $?;
                    exit $?;
                }
            fi
        else
            log_end_msg 0;
            exit 0;
        fi
        ;;
    restart|force-reload)
        # Stop the daemon.
        if [ -e $PIDFILE ]; then
            status_of_proc --pidfile $PIDFILE $DAEMON $NAME >/dev/null && status="0" || status="$?"
            if [ "$status" = "0" ]; then
                log_daemon_msg "Shutting down the process" "$NAME\n"
                start-stop-daemon --stop --quiet --oknodo --retry TERM/5/KILL/5 --pidfile $PIDFILE && {
                    log_end_msg 0;
                } || {
                    log_end_msg $?;
                    exit $?;
                }
            fi
        else
            log_warning_msg "Process $NAME is not running\n"
        fi
        # Start the daemon.
        log_daemon_msg "Restarting the process" "$NAME\n"
        start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --startas /bin/bash -- -c "exec $DAEMON $ARGS > $LOGFILE 2>&1"
        log_end_msg $?
        exit $?
        ;;
    status)
        log_daemon_msg "Checking for the process" "$NAME\n"
        # Check the status of the process.
        status_of_proc --pidfile $PIDFILE $DAEMON $NAME process && exit 0 || exit $?
        ;;
    *)
        log_warning_msg "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 3
esac